### ISSUE TITLE
Get a "ImportError: cannot import name 'IntEnum'"

### ISSUE THREAD

**Issue by fnielsen** [onnx/onnx-caffe2#1]
`onnx-caffe2` has a dependency on `enum` as specified in `setup.py`, but `enum` is already there in Python3.4 and Python3.5. The installation fails with `ImportError: cannot import name 'IntEnum'`.

**Comment by bddppq** [comment]
@fnielsen Thanks for reporting! :-) This should have been fixed now.

**Comment by fnielsen** [comment]
I can confirm that I now can install the pip versions successfully with python3.4 and python3.5.

Thanks for the swift response.
