### ISSUE TITLE
Duplicate OperatorSetId entries for ai.onnx

### ISSUE THREAD

**Issue by lutzroeder** [onnx/onnx-caffe2#267]
Models in the ONNX model zoo have duplicate `OperatorSetIdProto` entries for empty domain (`ai.onnx`) and `version: 3`.

![screenshot](https://user-images.githubusercontent.com/438516/36503280-6b00818e-1701-11e8-9064-6a7233388a96.png)

**Comment by houseroad** [comment]
We should be good now, just fixed the bug in our exporter and updated the models in our model zoo.
