### ISSUE TITLE
Does onnx-caffe2 support cudnn7 only?

### ISSUE THREAD

**Issue by wellingtonyl** [onnx/onnx-caffe2#288]
When I  run the following code:

prepared_backend = onnx_caffe2.backend.prepare(model, device="CUDA:0")

it happens:

RuntimeError: [enforce fail at common_cudnn.h:118] version_match. cuDNN compiled (6021) and runtime (7003) versions mismatch 

My cudnn version is 6.0.21， and I compile caffe2 with cudnn 6.0.21, why runtime cudnn version is 7.0.03? Does onnx-caffe2 support cudnn7 only?

**Comment by houseroad** [comment]
I also use CUDA 8 + CUDNN 6 (6.0.21) for development. There is not problem.

**Comment by bingwz** [comment]
hello, I got the same error , how do you solve it ?

**Comment by houseroad** [comment]
That means you may installed two versions of CuDNN. Please check your working environment and system to make sure there is only one CuDNN installed.
