### ISSUE TITLE
tutorial/example 

### ISSUE THREAD

**Issue by mbehrisch** [onnx/onnx-caffe2#3]
Hi,

would it be possible to get an example how to translate a valid caffe2 model into onnx?
Maybe this should go in the documentation README.md?!

Thanks

**Comment by jerryzh168** [comment]
For now, please take a look at https://github.com/onnx/onnx-caffe2/blob/master/tests/caffe2_ref_test.py for examples, we will write more tutorials/examples soon.

**Comment by bddppq** [comment]
Just to add, the c2 frontend is at https://github.com/onnx/onnx-caffe2/blob/master/onnx_caffe2/frontend.py.

You can translate a caffe2 model to onnx with just couple lines of code (these are extracted from the `caffe2_ref_test.py` @jerryzh168 mentioned above):
```
import onnx_caffe2.frontend as c2_onnx
from caffe2.proto import caffe2_pb2

c2_net = caffe2_pb2.NetDef()
with open(c2_model_file, 'rb') as f:
    c2_net.ParseFromString(f.read())
onnx_graph = c2_onnx.caffe2_net_to_onnx_graph(c2_net)
```

**Comment by mbehrisch** [comment]
Perfect. I just didn't think about looking into the unit tests. Maybe I should write more testing code myself :)
