### ISSUE TITLE
Interchangeable Device Ops from PyTorch

### ISSUE THREAD

**Issue by akurniawan** [onnx/onnx-caffe2#71]
In my use case, I trained a model in GPU environment, and later exported it with CPU for a reason. It ran perfectly when importing the model from onnx_caffe2.backend. However, when I actually ran the net, it threw an error stating the network expects CPUContext while the caller expects CUDAContext. I suspect it's because I exported the model in CPU env? Now I'm trying to export the net using GPU and see if this works. If that's really the case, is there any way we can interchangeably export and load it in any devices we want?

**Comment by bddppq** [comment]
Yes onnx model doesn't carry device information, so it should be able to be executed on any supported device.
What's the version of your onnx-caffe2 installation? There was a fix for running on GPU last week: https://github.com/onnx/onnx-caffe2/commit/15a2c6691dea6450f96862de4f75cb7d815b7484

**Comment by akurniawan** [comment]
I'm using the latest version from PIP (0.2.1). So I need to compile it from source if I want to use it?

**Comment by akurniawan** [comment]
Btw, this is the error message when I use exported model from CPU
`RuntimeError: [enforce fail at blob.h:76] IsType<T>(). wrong type for the Blob instance. Blob contains caffe2::Tensor<caffe2::CPUContext> while caller expects caffe2::Tensor<caffe2::CUDAContext> .
Offending Blob name: 2.
Error from operator: 
input: "1" input: "2" output: "780" name: "" type: "Conv" arg { name: "dilations" ints: 1 ints: 1 } arg { name: "strides" ints: 2 ints: 2 } arg { name: "pads" ints: 3 ints: 3 ints: 3 ints: 3 } arg { name: "group" i: 1 } arg { name: "kernels" ints: 7 ints: 7 } device_option { device_type: 1 cuda_gpu_id: 0 }
`

**Comment by bddppq** [comment]
Yep you need to install from source. onnx-caffe2 is a pure python package, so it should be pretty easy to install from source.

**Comment by akurniawan** [comment]
Okay, thanks. I'll try it now. Will let you know if this fix my problem

**Comment by akurniawan** [comment]
Hey @bddppq. Just want to let you know that the fix works! Thanks for the help!
